version: '3.8'

services:
  db:
    image: timescale/timescaledb:latest-pg14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - psql-data:/var/lib/postgresql/data

  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - mqtt-config:/mosquitto/config

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/nginx/templates:/etc/nginx/templates
      - ./frontend/app/build:/usr/share/nginx/html
    depends_on:
      - vouch
    ports:
      - "80:80"
      #- "443:443"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      #args:
      #  - API_PORT=3000
      #   DB_HOST:
      #   DB_PORT:
      #   DB_DIALECT:
      #   POSTGRES_DB:
      #   POSTGRES_USER:
      #   POSTGRES_PASSWORD:
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      - API_PORT
      - DB_HOST
      - DB_PORT
      - DB_DIALECT
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      
volumes:
  psql-data: {}
  mqtt-config: {}
  grafana-data: {}
