services:
#  mongo:
#    image: mongo
#    restart: always
#    volumes:
#      - db-data:/data/db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example

  db:
    image: timescale/timescaledb:latest-pg14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=example
    volumes:
      - psql-data:/var/lib/postgresql/data 

  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - mqtt-config:/mosquitto/config

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-mongodb-datasource
    volumes:
      - grafana-data:/var/lib/grafana

# To be used later for reverse-proxy
#  nginx:
#    image: nginx
#    ports:
#      - "80:80"    
#      - "443:443"
    
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./frontend/app:/app
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - ./backend:/app

volumes:
  psql-data: {}
  mqtt-config: {}
  grafana-data: {}